name: user_reg_form
description: Flutter user registration app with form validation and navigation
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.png"